site_name: Beckett
theme: readthedocs

pages:
    - Home: 'index.md'
    - Getting Started: 'intro.md'
    - Resources: 'resources.md'
    - Clients: 'clients.md'
    - Advanced Features: 'advanced.md'
